import { Injectable } from '@nestjs/common'
import { PrismaService } from 'src/prisma/prisma.service'
import { Response } from 'express'
import PDFDocument from 'pdfkit'

@Injectable()
export class ReportsService {
  constructor(private prisma: PrismaService) {}

  async generateTaskReport(
    startDate: string,
    endDate: string,
    userId: string,
    res: Response,
  ) {
    // 🧠 STEP 1: FETCH DATA
    const tasks = await this.prisma.task.findMany({
      where: {
        createdAt: {
          gte: new Date(startDate),
          lte: new Date(endDate),
        },
        ...(userId && { assignedToId: userId }),
      },
      include: {
        assignedTo: true,
        project: true,
      },
      orderBy: {
        createdAt: 'desc',
      },
    })

    // 🧠 STEP 2: SUMMARY CALCULATION
    const totalTasks = tasks.length
    const completed = tasks.filter(t => t.status === 'COMPLETED').length
    const confirmed = tasks.filter(t => t.status === 'CONFIRMED').length
    const pending = tasks.filter(t => t.status !== 'COMPLETED' && t.status !== 'CONFIRMED').length

    const totalHours = tasks.reduce((sum, t) => {
      return sum + (t.timeSpentHours || 0)
    }, 0)

    // 🧠 STEP 3: USER NAME (FOR TITLE)
    let userName = 'Team'
    if (userId && tasks[0]?.assignedTo) {
     userName = `${tasks[0].assignedTo.firstName} ${tasks[0].assignedTo.lastName}`
    }

    // 📄 STEP 4: CREATE PDF
    const doc = new PDFDocument({ margin: 40 })

    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader(
      'Content-Disposition',
      `attachment; filename=report.pdf`,
    )

    doc.pipe(res)

    // 🏢 HEADER (TEMPLATE MATCH)
    doc.fontSize(12).text('DIGITAL PERSONAS PVT LTD')
    doc.text('703, Gowra Fountainhead')
    doc.text('Hitech City, Hyderabad')
    doc.moveDown()

    // ➖ LINE
    doc.moveTo(40, doc.y).lineTo(550, doc.y).stroke()

    // 📌 TITLE
    doc.moveDown()
    doc.fontSize(16).text(
      `${userName} – Performance Report`,
      { align: 'center' },
    )

    doc.fontSize(10).text(
      `${startDate} to ${endDate}`,
      { align: 'center' },
    )

    doc.moveDown()

    // 📊 SUMMARY
    doc.fontSize(12).text('Summary')
    doc.moveDown(0.5)

    doc.text(`Total Tasks: ${totalTasks}`)
    doc.text(`Completed: ${completed}`)
    doc.text(`Confirmed: ${confirmed}`)
    doc.text(`Pending: ${pending}`)
    doc.text(`Total Time: ${totalHours} hrs`)

    doc.moveDown()

    // 📋 TABLE HEADER
    doc.fontSize(11).text('Tasks')
    doc.moveDown(0.5)

    // Table Columns
    doc.fontSize(9)
    doc.text('Title', 40, doc.y, { continued: true })
    doc.text('Status', 200, doc.y, { continued: true })
    doc.text('User', 300, doc.y, { continued: true })
    doc.text('Time', 400, doc.y)

    doc.moveDown(0.5)

    // ➖ LINE
    doc.moveTo(40, doc.y).lineTo(550, doc.y).stroke()

    // 📋 TABLE ROWS
    tasks.forEach(task => {
      doc.moveDown(0.5)

      doc.text(task.title, 40, doc.y, { width: 140 })
      doc.text(task.status, 200, doc.y)
     const fullName = task.assignedTo
  ? `${task.assignedTo.firstName} ${task.assignedTo.lastName}`
  : '-'

doc.text(fullName, 300, doc.y)
      doc.text(
        task.timeSpentHours
          ? `${task.timeSpentHours} hrs`
          : task.timeSpentDays
          ? `${task.timeSpentDays} days`
          : '-',
        400,
        doc.y,
      )
    })

    // 📌 FOOTER
    doc.moveDown(2)
    doc.fontSize(8).text(
      'Generated by Task Analytics System',
      { align: 'center' },
    )

    doc.end()
  }
}