ALTER TYPE "KpiAssignmentStatus" ADD VALUE IF NOT EXISTS 'SELF_ASSESSMENT_SUBMITTED';

ALTER TABLE "KpiAssignment"
ADD COLUMN IF NOT EXISTS "selfSubmittedAt" TIMESTAMP(3);

ALTER TABLE "KpiAssignmentItem"
ADD COLUMN IF NOT EXISTS "employeeScore" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "employeeComments" TEXT;
